name: sana_ai
description: A fully offline Hinglish voice assistant.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # LLM & Voice
  llama_sdk: ^0.0.5
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5

  # Networking & Storage
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png